### ISSUE TITLE
Cannot instantiate interface Github_HttpClientInterface

### ISSUE THREAD

**Issue by WilHall** [ornicar/php-github-api#11]
Fatal Error: Cannot instantiate interface Github_HttpClientInterface in lib/Github/Client.php on line 56

When constructing a new API object, the above error is thrown.

Example code:
    //Register GitHub Autoloader
    require_once 'lib/Github/Autoloader.php';
    Github_Autoloader::register();

```
// Create api object and authenticate
$github = new Github_Client();
$github->authenticate($git_username, $git_secret);
```

**Comment by ornicar** [comment]
Fixed. I don't know how I missed that!

**Comment by WilHall** [comment]
I made the exact change you did in attempt to fix the error before creating this issue. However, it fails with the same error. Just to be sure I downloaded and replaced my copy with the newest version, but still failing with the same error. By the way, the environment is PHP 5.2 via Apache 2 running on Unix.

**Comment by ornicar** [comment]
The line 56 now instantiates `Github_HttpClient_Curl`. How can you get the same error?

Plus, before my fix the tests were failing with the error you mentioned. They are now passing.

**Comment by WilHall** [comment]
My apologies, the page was cached. Tested now and it works. However, throws the error:

Fatal error: Class 'phpGitHubApi' not found in lib/Github/HttpClient/Curl.php on line 27

Wasn't "phpGitHubApi" changed in this version?

**Comment by WilHall** [comment]
Fixed. Replaced lines 26-43 in Curl.php:

```
        switch ($options['auth_method']) {
            case phpGitHubApi::AUTH_HTTP_PASSWORD:
                $curlOptions += array(
                    CURLOPT_USERPWD => $options['login'].':'.$options['secret'],
                );
                break;
            case phpGitHubApi::AUTH_HTTP_TOKEN:
                $curlOptions += array(
                    CURLOPT_USERPWD => $options['login'].'/token:'.$options['secret'],
                );
                break;
            case phpGitHubApi::AUTH_URL_TOKEN:
            default:
                $parameters = array_merge(array(
                    'login' => $options['login'],
                    'token' => $options['secret']
                        ), $parameters);
                break;
```

With:

```
        switch ($options['auth_method']) {
            case Github_Client::AUTH_HTTP_PASSWORD:
                $curlOptions += array(
                    CURLOPT_USERPWD => $options['login'].':'.$options['secret'],
                );
                break;
            case Github_Client::AUTH_HTTP_TOKEN:
                $curlOptions += array(
                    CURLOPT_USERPWD => $options['login'].'/token:'.$options['secret'],
                );
                break;
            case Github_Client::AUTH_URL_TOKEN:
            default:
                $parameters = array_merge(array(
                    'login' => $options['login'],
                    'token' => $options['secret']
                        ), $parameters);
                break;
```

Tested it, and requests are working now.

**Comment by ornicar** [comment]
Thanks again, I am writing a test for it.

**Comment by ornicar** [comment]
Fixed. I released version 3.1.
